### ISSUE TITLE
Please comment on this project to improve it.💝

### ISSUE THREAD

**Issue by ranjeetrocky** [ranjeetrocky/blurry_container#1]

**Comment by yelkamel** [comment]
It's will be great if we can blur progressively with an animated controller. =)

**Comment by holy-dev** [comment]
Null safety?

**Comment by golnarSheikhBahaie** [comment]
hey there thnx 4 great repo . i wonder how can i remove the text ?? ( child will be here )

**Comment by milodude** [comment]
Is it possible to have an option, when the user clicks on the blurry container, automatically dismiss it without calling the controller?
