### ISSUE TITLE
dosen't support null safety

### ISSUE THREAD

**Issue by Arpit-Sahu** [ranjeetrocky/blurry_container#3]

**Comment by ken-ng-esotec** [comment]
Viral had a PR merged for 0.0.2. Can you please release a new version?

**Comment by ken-ng-esotec** [comment]
@ranjeetrocky can you please merge

**Comment by ranjeetrocky** [comment]
> @ranjeetrocky can you please merge

Hello @ken-ng-esotec it is fixed now
