### ISSUE TITLE
Extremely expensive to render

### ISSUE THREAD

**Issue by ibraheemalayan** [ranjeetrocky/blurry_container#5]
rendering frames containing only 5 BlurryContainers increases raster time from `4ms` up to `75ms` making the whole app janky:

### With a normal colored container
<img width="861" alt="Screenshot 2023-07-24 at 17 38 11" src="https://github.com/ranjeetrocky/blurry_container/assets/35265448/f1703f74-e21e-42d2-a006-25a3b5fd97db">

### With a BlurryContainer
<img width="999" alt="Screenshot 2023-07-24 at 16 28 51" src="https://github.com/ranjeetrocky/blurry_container/assets/35265448/a2741c9b-dcdb-48b5-9ffe-a298cb842391">

**Comment by kishan-dhankecha** [comment]
We are using barebone widgets that Flutter provided!

Make sure to use a smaller value for the `blur` parameter. If you still have janking issue make sure your widget trees are fairly simple. I have tested this with a `ListView.separated` with 20 `BlurryContainer` widgets. It runs quite smoothly even in debug mode!


![image](https://github.com/ranjeetrocky/blurry_container/assets/68430205/bb9826e9-0cc3-4156-9162-8c9d810247e7)

Here is my code (It is not as complicated as a real-world use case but it is something)

<details><summary>Code sample</summary>

```dart
import 'package:blurrycontainer/blurrycontainer.dart';
import 'package:flutter/material.dart';

import 'shared/app_state.dart';

Future<void> mainBase(Flavor flavor) async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyWidget());
}

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: const Color(0xFF21262d),
        body: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            const Positioned(
              top: 220,
              left: 10,
              child: GradientBall(colors: [Colors.deepOrange, Colors.amber]),
            ),
            const Positioned(
              top: 400,
              right: 10,
              child: GradientBall(
                size: Size.square(200),
                colors: [Colors.blue, Colors.purple],
              ),
            ),
            ListView.separated(
              padding: const EdgeInsets.all(16),
              itemCount: 20,
              separatorBuilder: (context, index) => const SizedBox(height: 22),
              itemBuilder: (context, index) {
                return BlurryContainer(
                  blur: 8,
                  height: 240,
                  elevation: 4,
                  elevationColor: Colors.black,
                  borderRadius: BorderRadius.circular(32),
                  color: Colors.white.withOpacity(.1),
                  padding: const EdgeInsets.all(32),
                  child: Center(
                    child: Text(
                      'Item $index',
                      style: const TextStyle(
                        fontSize: 24,
                        color: Colors.white,
                      ),
                    ),
                  ),
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

class GradientBall extends StatelessWidget {
  final List<Color> colors;
  final Size size;
  const GradientBall({
    super.key,
    required this.colors,
    this.size = const Size.square(150),
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      height: size.height,
      width: size.width,
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        gradient: LinearGradient(
          colors: colors,
        ),
      ),
    );
  }
}
```

</details>



If you still want faster render and smooth frames without janks then unfortunately we have to wait until flutter itself improves it.

**Comment by ibraheemalayan** [comment]
Why would you mark this as won't fix ?
your library offers a great feature but its implementation needs to change to be actually useful.
using it in any application causes serious performance issues and makes the app very laggy. 

there has to be another way to implement it without this much cost.

**Comment by kishan-dhankecha** [comment]
@ibraheemalayan Please refer to my explanation above. If you are not satisfied with that and have some other way to do this performance improvement you can elaborate here. I will implement a solution if I can and also any PR related to this will be considered.

Thanks.
